biblio3:
  features: logging
  l10n: ru
  projectFileStructure: {}
  modules:
  - core:
      entities:
      - users
      - categories
  application:
  - _welcome_
  - _pubmed_
  - _compact_view_
  - _detailed_view_
  - _publication_cat_
  - attachments
  - publications
  - publication2project
  scripts:
  - Post-db
  - test
  - dictionaries
  includes:
  - common