biblio3:
  features: logging
  l10n: ru
  projectFileStructure: {}
  modules:
  - core:
      entities:
      - users
      - categories
  application:
  - _welcome_
  - _pubmed_
  - _publication_cat_
  - attachments
  - publications
  scripts:
  - Post-db
  - dictionaries
